New variables accepted and new init script (the previous one failed to accurately report the status of the daemon).

diff --git a/templates/btsync b/templates/btsync
--- a/templates/btsync
+++ b/templates/btsync
@@ -1,71 +1,155 @@
-#!/bin/sh
+#! /bin/sh
 ### BEGIN INIT INFO
-# Provides: btsync
-# Required-Start: $local_fs $remote_fs
-# Required-Stop: $local_fs $remote_fs
+# Provides:          btsync
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
 # Should-Start: $network
 # Should-Stop: $network
-# Default-Start: 2 3 4 5
-# Default-Stop: 0 1 6
-# Short-Description: Multi-user daemonized version of btsync.
-# Description: Starts the btsync daemon for all registered users.
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Bit Torrent Sync service
+# Description:       This script provides basic start/stop commands for the btsync daemon.
 ### END INIT INFO
 
-# Replace with linux users you want to run BTSync clients for
-BTSYNC_USERS="{{ btsync_user }}"
+# Author: Raphael Lorenzeto <raphael.lorenzeto@gmail.com>
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="Description of the service"
+NAME=btsync
 DAEMON=/usr/local/bin/btsync
+DAEMON_ARGS="--config {{ btsync_config_path }}/config.json"
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
 
-start() {
-  for btsuser in $BTSYNC_USERS; do
-    HOMEDIR=`getent passwd $btsuser | cut -d: -f6`
-    config=$HOMEDIR/.sync/config.json
-    if [ -f $config ]; then
-      echo "Starting BTSync for $btsuser"
-      start-stop-daemon -b -o -c $btsuser -S -u $btsuser -x $DAEMON -- --config $config
-    else
-      echo "Couldn't start BTSync for $btsuser (no $config found)"
-    fi
-  done
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+  # Return
+  #   0 if daemon has been started
+  #   1 if daemon was already running
+  #   2 if daemon could not be started
+  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+    || return 1
+  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+    $DAEMON_ARGS \
+    || return 2
+  # Add code here, if necessary, that waits for the process to be ready
+  # to handle requests from services started subsequently which depend
+  # on this one.  As a last resort, sleep for some time.
 }
 
-stop() {
-  for btsuser in $BTSYNC_USERS; do
-    dbpid=`pgrep -fu $btsuser $DAEMON`
-    if [ ! -z "$dbpid" ]; then
-      echo "Stopping btsync for $btsuser"
-      start-stop-daemon -o -c $btsuser -K -u $btsuser -x $DAEMON
-    fi
-  done
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+  # Return
+  #   0 if daemon has been stopped
+  #   1 if daemon was already stopped
+  #   2 if daemon could not be stopped
+  #   other if a failure occurred
+  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+  RETVAL="$?"
+  [ "$RETVAL" = 2 ] && return 2
+  # Wait for children to finish too if this is a daemon that forks
+  # and if the daemon is only ever run from this initscript.
+  # If the above conditions are not satisfied then add some other code
+  # that waits for the process to drop all resources that could be
+  # needed by services started subsequently.  A last resort is to
+  # sleep for some time.
+  start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+  [ "$?" = 2 ] && return 2
+  # Many daemons don't delete their pidfiles when they exit.
+  rm -f $PIDFILE
+  return "$RETVAL"
 }
 
-status() {
-  for btsuser in $BTSYNC_USERS; do
-    dbpid=`pgrep -fu $btsuser $DAEMON`
-    if [ -z "$dbpid" ]; then
-      echo "btsync for USER $btsuser: not running."
-    else
-      echo "btsync for USER $btsuser: running (pid $dbpid)"
-    fi
-  done
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+  #
+  # If the daemon can reload its configuration without
+  # restarting (for example, when it is sent a SIGHUP),
+  # then implement that here.
+  #
+  start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+  return 0
 }
 
 case "$1" in
   start)
-    start
-    ;;
+  [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+  do_start
+  case "$?" in
+    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+  esac
+  ;;
   stop)
-    stop
-    ;;
-  restart|reload|force-reload)
-    stop
-    start
-    ;;
+  [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+  do_stop
+  case "$?" in
+    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+  esac
+  ;;
   status)
-    status
+  status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+  ;;
+  #reload|force-reload)
+  #
+  # If do_reload() is not implemented then leave this commented out
+  # and leave 'force-reload' as an alias for 'restart'.
+  #
+  #log_daemon_msg "Reloading $DESC" "$NAME"
+  #do_reload
+  #log_end_msg $?
+  #;;
+  restart|force-reload)
+  #
+  # If the "reload" option is implemented then remove the
+  # 'force-reload' alias
+  #
+  log_daemon_msg "Restarting $DESC" "$NAME"
+  do_stop
+  case "$?" in
+    0|1)
+    do_start
+    case "$?" in
+      0) log_end_msg 0 ;;
+      1) log_end_msg 1 ;; # Old process is still running
+      *) log_end_msg 1 ;; # Failed to start
+    esac
     ;;
+    *)
+    # Failed to stop
+    log_end_msg 1
+    ;;
+  esac
+  ;;
   *)
-    echo "Usage: /etc/init.d/btsync {start|stop|reload|force-reload|restart|status}"
-    exit 1
+  #echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+  echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+  exit 3
+  ;;
 esac
 
-exit 0
+:
